name: Publish Node Docker
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run:
        echo "${{ secret.DOCKERPASSWORD }}" | docker login -u
        "${{ secret.DOCKERUSERNAME }}" --password-stdin   
        docker image build -t "${{ secret.DOCKERUSERNAME }}/
        EGCI:latest"
        docker push "${{ secret.DOCKERUSERNAME }}/EGCI:latest"
